name: Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Set up go
              uses: actions/setup-go@v2
              with:
                go-version: "1.22"

            - name: Checkout repository and submodules
              uses: actions/checkout@v2

            - name: Build
              run: scripts/buildprod.sh

            - name: Authenticate to Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

            - name: Set up gcloud Cloud SDK environment
              uses: google-github-actions/setup-gcloud@v2.1.0



            - name: gcloud builds submit
              run: gcloud builds submit --project notely --tag europe-west2-docker.pkg.dev/continual-voice-426607-k9/notely-ar-repo/notely .
