name: Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Set up go
              uses: actions/setup-go@v2
              with:
                go-version: "1.22"

            - name: Checkout repository and submodules
              uses: actions/checkout@v2

            - name: Build
              run: scripts/buildprod.sh

            - name: Google Cloud
              run: gcloud builds submit --tag europe-west2-docker.pkg.dev/continual-voice-426607-k9/notely-ar-repo/notely .
