name: Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Set up go
              uses: actions/setup-go@v2
              with:
                go-version: "1.20"

            - name: Checkout repository and submodules
              uses: actions/checkout@v2
              with:
                submodules: recursive
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Build
              run: scripts/buildprod.sh
